run:
  include:
    - "cmd"
    - "ent/schema"
    - "graph/*.resolvers.go"
    - "internal"
  tests: true
  timeout: 5m
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - ineffassign
issues:
  exclude-rules:
    - linters:
        - errcheck
      text: "error return value not checked"
output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true