package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"sandbox-gql/ent"
	"sandbox-gql/graph/model"
	"strconv"
)

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input model.CreateAccountInput) (*model.Account, error) {
	entInput := ent.CreateAccountInput{
		Name:  input.Name,
		Email: input.Email,
	}
	entAccount, err := r.client.Account.Create().SetInput(entInput).Save(ctx)
	if err != nil {
		return nil, err
	}
	return &model.Account{
		ID:    strconv.Itoa(entAccount.ID),
		Name:  entAccount.Name,
		Email: entAccount.Email,
	}, nil
}

// UpdateAccount is the resolver for the updateAccount field.
func (r *mutationResolver) UpdateAccount(ctx context.Context, id string, input model.UpdateAccountInput) (*model.Account, error) {
	panic(fmt.Errorf("not implemented: UpdateAccount - updateAccount"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
