// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (a *Account) Items(ctx context.Context) (result []*Item, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = a.NamedItems(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = a.Edges.ItemsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = a.QueryItems().All(ctx)
	}
	return result, err
}

func (i *Item) Account(ctx context.Context) (*Account, error) {
	result, err := i.Edges.AccountOrErr()
	if IsNotLoaded(err) {
		result, err = i.QueryAccount().Only(ctx)
	}
	return result, MaskNotFound(err)
}
