name: Lint and Format

on: [push, pull_request]

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and lint using Docker
      run: |
        docker build --target linter -t myapp-linter .